### ISSUE TITLE
I want to offer one more idea.

### ISSUE THREAD

**Issue by mehmetgokkaya** [FlorianLeChat/YouTube-Downloader#2]
Can you show the time when converting from video to mp3? 
There are those who show it as a percentage. youtube-dl supports this. Just an idea. I'm working on this too.
![Screenshot](https://user-images.githubusercontent.com/27200160/196210268-5b285695-a357-4f56-89ed-7585ca3a42f6.png)

**Comment by FlorianLeChat** [comment]
To be honest, I didn't initially think about this kind of thing because my server is very fast for uploading and converting videos so it felt unnecessary, and since it was more of a personal project that seemed to be fine for me. I'll look into it in the next few days and see if I have a solution while avoid overloading the project with code because I want to keep it fairly light. If you have a solution on your side, please make a pull request or suggest me anything, thank you!

**Comment by FlorianLeChat** [comment]
Sorry for the downtime, I doubt the library I'm using has a "magic" function to tell me the progress of the YouTube-DL download/conversion without reloading the page (because of PHP) or using AJAX (which could make the project heavier).

My only hint is about this function: https://github.com/norkunas/youtube-dl-php/blob/master/src/YoutubeDl.php#L94-L181, I'll take a look at it this week-end and I'll tell you if a workaround is possible or not.

**Comment by FlorianLeChat** [comment]
I'm sorry but this idea can't be fulfilled even though it's very good. I tried to apply what is suggested by the library but unfortunately I have to play with PHP output buffering and numerous inconsistencies (of configuration and behavior) between PHP server and web servers (Apache, Nginx, etc.). If someone has a suggestion or if you want to make a pull request, you are welcome but unfortunately I can't spend more time for that on a project which is not intended to be very sophisticated.

**Comment by FlorianLeChat** [comment]
I'm sorry but this idea can't be fulfilled even though it's very good. I tried to apply what is suggested by the library but unfortunately I have to play with PHP output buffering and numerous inconsistencies (of configuration and behavior) between PHP server and web servers (Apache, Nginx, etc.). If someone has a suggestion or if you want to make a pull request, you are welcome but unfortunately I can't spend more time for that on a project which is not intended to be very sophisticated.
